(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.Blk = function() {
	this.initialize(img.Blk);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.HeadShot = function() {
	this.initialize(img.HeadShot);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,207,207);


(lib.NewBG = function() {
	this.initialize(img.NewBG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,1200);


(lib.ProductShot = function() {
	this.initialize(img.ProductShot);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,1200);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.zoomOutCover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A9hdhQsOsOAAxTQAAxRMOsPQMPsPRSAAQRTAAMOMPQMPMPAARRQAARTsPMOQsOMPxTAAQxSAAsPsPg");
	this.shape.setTransform(267.2,267.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.zoomOutCover, new cjs.Rectangle(0,0,534.4,534.4), null);


(lib.White = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AriB/IAAj+IXFAAIAAD+g");
	mask.setTransform(72.8,7.5);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape.setTransform(119.3,33,0.521,0.521);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQgBgVAQgQIABgBIgBAAQAQgQAXAAQAWAAARAQQAQAQAAAWQAAAXgQAPIAAABQgQAQgXAAQgWAAgQgQgAgYgbQgLALgBAQIAAAAQgBAQALALQAKALAQABIAAAAQAQABALgLQAMgLABgQQABgPgLgMQgLgLgQgBIgCAAQgOAAgLAKg");
	this.shape_1.setTransform(112.7,33.1,0.521,0.521);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("AgIBSIAAhlIARAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_2.setTransform(107.8,31.5,0.521,0.521);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("AgIBIIAAhXIgTAAIAAgPIATAAIAAgoIAQAAIAAAoIATAAIAAAPIgTAAIAABXg");
	this.shape_3.setTransform(104.8,32.1,0.521,0.521);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_4.setTransform(101.8,31.5,0.521,0.521);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AglBJQgNgPAAgYQAAgZANgOQAOgPAVAAQALgBAKAHQAKAGAFAKIAAhZIARAAIAACrIgQAAIAAgSQgFAKgLAGQgKAGgKAAQgWAAgOgPgAgXAGQgJAJAAARQAAATAJAKQAJALAOAAQAQAAAJgKQAKgKAAgSQAAgSgKgKQgJgJgQAAQgOAAgJAJg");
	this.shape_5.setTransform(96.8,31.4,0.521,0.521);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AgqBSIAAiiIBVAAIAAASIhBAAIAAAuIBBAAIAAARIhBAAIAAA/IBBAAIAAASg");
	this.shape_6.setTransform(90.7,31.5,0.521,0.521);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AgIBWIAAirIARAAIAACrg");
	this.shape_7.setTransform(83,31.3,0.521,0.521);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("AglAoQgNgPAAgZQAAgYANgPQANgPAWAAQALAAAKAGQAKAGAFALIAAgTIARAAIAABlIgQAAIAAgTQgFALgLAGQgKAGgKAAQgWAAgOgPgAgXgbQgJAKAAARQAAARAJAKQAJALAPAAQAQAAAJgKQAJgKAAgRQAAgRgKgKQgKgKgPAAQgPAAgIAJg");
	this.shape_8.setTransform(78,33.1,0.521,0.521);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape_9.setTransform(71.5,33,0.521,0.521);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_10.setTransform(64.7,33.1,0.521,0.521);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_11.setTransform(59.9,31.5,0.521,0.521);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#999999").s().p("AgUAyQgMgGgFgLIANgJQAEAIAHAEQAIAFAGgBQAJAAAGgEQAEgFAAgGQAAgGgDgEQgDgCgJgDQgWgJgHgDQgKgHAAgNQAAgOAJgIQALgJAOAAQAMgCAKAGQAKAGAFAKIgOAJQgDgHgHgEQgGgEgHAAQgGAAgFAEQgFAEgBAGIAAABQABAHAGAEQADACAQAEQAPAFAHAGQAHAHAAALQABAPgLAJQgKAJgRAAIgCAAQgLAAgIgFg");
	this.shape_12.setTransform(56.1,33.1,0.521,0.521);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#999999").s().p("AgVAyQgLgGgGgLIAPgJQAHARASgBQAIAAAGgEQAFgFAAgGQAAgGgEgEQgEgCgIgDQgXgJgFgDQgLgHAAgNQAAgOAKgIQAKgJAPAAQALgCAKAGQAKAGAFAKIgOAJQgHgQgQABQgFgBgGAEQgEAEgBAHIAAABQgBAHAHAEQADACAQAEQAPAFAHAGQAHAHABALQAAAPgKAJQgLAJgQAAIgDAAQgKAAgKgFg");
	this.shape_13.setTransform(51.2,33.1,0.521,0.521);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#999999").s().p("AACA3QgWAAgOgPQgPgQAAgYQAAgYAOgPQAOgPAWAAQAWAAANAPQAOAOAAAZIAAACIhQAAIAAACQgBAOAJALQAIALAOABIADAAQAXgBAKgVIANAJQgHANgNAHQgLAHgOAAIgCAAgAgUgfQgJAIgBAMIA9AAQAAgLgIgJQgIgIgMAAIgDAAIgBAAQgLAAgIAIg");
	this.shape_14.setTransform(45.8,33.2,0.521,0.521);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#999999").s().p("AgMBXIAAhXIgTAAIAAgOIATAAIAAgdQABgYAFgJQAGgKARAAQAGAAAJACIAAASQgFgDgJAAQgJAAgDAHQgBAEAAARIAAAcIAbAAIAAANIgbAAIAABXg");
	this.shape_15.setTransform(41.1,31.2,0.521,0.521);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_16.setTransform(35.9,33.1,0.521,0.521);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#999999").s().p("AgeA1IAAhmIAQAAIAAAWQAHgNAHgGQAHgGAMAAQAGAAAGACIgGAQIgLgCQgbAAAAAnIAAAyg");
	this.shape_17.setTransform(30.9,33.1,0.521,0.521);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#999999").s().p("AgtBSIAAiiIAiAAQAdgBALAJQAPANACAUQABAVgNAOIgFAEQgHAFgLADIgWABIgPAAIAABJgAgagIIAKAAQAWAAAJgFQAKgGAAgPQAAgQgKgHQgKgGgVABIgKAAg");
	this.shape_18.setTransform(25.9,31.5,0.521,0.521);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9D9D9C").s().p("AnWCpIAAioQAAglAagbQAbgbAlAAIAHAAQAlABAZAbQAZAbgBAkQgBAmgbAaQgcAbgmgBIgxAAIAABOgAmhgjQgOAQAAAUIAAAzIAzAAQAWAAAPgPQAQgQgBgVQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgUgQgOQgPgOgVAAIgBAAQgVABgPAQgAD1BAQgbgaABgmQAAgkAagbQAbgbAlAAQAmAAAbAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgmAAgbgbgAESglQgPAPgBAVQAAAVAPARQAPAQAWABIABAAQAWgBAPgQQAPgPgBgWIAAAAQAAgVgPgQQgPgQgWAAQgVABgPAPgAjyBBQgbgagBgmQAAglAagbQAbgbAlAAQAmgBAbAbQAbAaABAmIgCANIiMAAQAEASAOANQAPAMASgBQAdAAAZgSIAWAcQghAagpAAIgBAAIgCAAQglAAgagagAjRgsQgNAKgGARIBiAAQgFgQgNgLQgNgKgRAAQgRAAgOAKgAMNBbQgmAAgagbQgbgaAAglIABgBQgBgkAagbQAagbAlAAIACAAQAhgBAZAXIgXAaQgQgMgUABQgWACgPAQQgOARABAVQABAUAOAOQAOAPAVACQAUACAPgNIAZAZQgYAXggAAIgDAAgAAxA/IAVgbQAaARAgADQAgAAAAgRQAAgIgRgHIglgLQg2gPAAgjQAAgWATgPQAUgPAfAAQAmAAAfATIgUAbQgWgLgagBQgdAAAAARQAAAIA1AQQA1APAAAiQAAAbgYAPQgUANgdABQgrgCgjgagApGBbQglAAgZgZQgbgaAAgsIAAhTIAoAAIAABTQAAAbAPAPQAOAOAVABQAVgBAOgOQAPgPAAgbIAAhTIAoAAIAABTQAAArgbAaQgZAZglABgAtHA/IAWgbQAZARAhADQAfAAAAgRQAAgIgRgHIglgLQg1gPAAgjQAAgWATgPQAUgPAfAAQAlAAAgATIgUAbQgXgLgagBQgdAAAAARQAAAHARAGIAlALQA1APAAAiQAAAbgYAPQgVANgdABQgqgCgkgagAGmgHQABgkAcgaQAbgZAlABQAkABAaAbQAZAbgBAlIAABYIgoAAIAAhWQABgFgBgGQgCgUgRgNQgQgNgVACQgUADgNAQQgNAQACAUIAABWIgnABgAhDBYIAAhZQABgmAbgZQAbgbAlABIAJAAIAAAlQgHgBgIACQguAIAAAwIAABUgAJ1BXIAAiuIAoAAIAACugAKKh6QgJAAgHgGQgHgIAAgJQAAgJAHgHQAHgHAJAAQAKAAAGAHQAHAHAAAJQAAAJgGAIQgHAGgJAAg");
	this.shape_19.setTransform(100.4,9.4,0.521,0.521);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgSBFQgNgDgLgKIAMgQQALAHANACQAQAAAIgOQAEgJAAgMQgKAJgMAAQgSAAgOgNQgOgNAAgTIAAgvIAZAAIAAAuQAAAJAGAHQAGAHAJAAQAJAAAHgHQAGgHABgJIAAguIAZAAIAAAuQgBArgEAPQgHAcgbAGQgHABgGAAQgHAAgHgBg");
	this.shape_20.setTransform(15.6,11.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgJBbQglgGgdgWIAXgfQALAIASAGQAXAHAQgFQALgCACgHQACgGgHgFIgggKQgbgHgNgIQgQgIgFgRQgFgRAIgRQANgYAfgIQAQgDAMACQAhABAdATIgXAfQgdgNgfAEQgIACgCAFQgCAGAGADIAAAAQAFAFAZAHQAcAHAMAGQAcAOgBAcQgBASgJALQgRAVgfAFg");
	this.shape_21.setTransform(25.3,9.4,0.521,0.521);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AArBZIAAhXQAAgRgNgMQgMgNgSAAQgRAAgNANQgMAMAAARIAABXIgvAAIAAhXQgBglAbgaQAbgbAkAAQAlAAAbAbQAaAaABAlIAABXg");
	this.shape_22.setTransform(45.2,9.3,0.521,0.521);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag/BAQgbgaAAgmQAAgkAbgbQAagaAlgBQAmAAAaAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgkAAgbgbgAgdgdQgNAMAAARQAAASAMANQANANARAAQASAAANgNQAMgNAAgSQAAgRgMgMQgNgNgSAAQgRAAgMANg");
	this.shape_23.setTransform(34.7,9.3,0.521,0.521);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag/BtQgbgbAAglQAAgmAagaQAbgaAlgBIArAAIAAhYIAwAAIAACyQgBAmgaAbQgbAaglAAQglAAgagagAgeAOQgMAMAAASQAAASAMANQANAMARAAQARAAANgMQANgNAAgSIgBgrIgqAAQgRAAgNANg");
	this.shape_24.setTransform(4.7,7.1,0.521,0.521);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.White, new cjs.Rectangle(0,0,144.2,20.2), null);


(lib.Text = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("ALRBPIAUgqIgchAIAOAAIAVAzIAWgzIANAAIgvBqgAN7AsQgGgDgFgFQgEgFgDgHQgCgHAAgJQAAgIACgHQADgHAEgFQAFgFAGgDQAGgCAIAAIAIABIAHADIAGAFIAFAHIAAgOIAMAAIAABHIgMAAIAAgNIgFAHIgGAFIgHADIgHABQgIAAgHgDgAOCgPQgFABgDAEQgDADgBAFQgCADAAAHQAAAGACAFQABAFADAEQAEADAEACQAEACAGAAQAFAAAEgCQAFgCADgDQADgDABgFQACgFAAgGQAAgGgCgEQgCgFgCgEQgDgDgFgCQgFgCgFAAQgFAAgEACgAMqAsQgHgDgEgFQgFgFgDgHQgDgIABgIQgBgIADgHQADgHAFgFQAEgFAGgDQAHgCAIAAQAIAAAGACQAGADAFAFQAEAFADAGQADAIAAAHIAAADIg6AAIAAABQAAAGACAEQACAFADAEQADADAFACQAEACAGAAQAGAAAGgEQAGgEAEgIIAKAGIgGAJQgDADgFADIgJAEIgKABQgJAAgGgDgANNAAQAAgEgBgEIgFgGQgDgCgEgBQgDgCgFAAQgFAAgDACQgFABgDADIgEAGQgCADgBAEIAsAAIAAAAgAJjAsQgHgDgEgFQgFgFgDgHQgCgIAAgIQAAgIACgHQADgHAFgFQAEgFAGgDQAHgCAIAAQAIAAAGACQAHADAEAFQAEAFADAGQACAIAAAHIAAADIg5AAIAAABQAAAGACAEQACAFAEAEQADADAEACQAEACAGAAQAGAAAGgEQAGgEAEgIIAKAGIgGAJQgEADgEADIgJAEIgKABQgJAAgGgDgAKGAAQAAgEgBgEIgFgGQgDgCgEgBQgDgCgFAAQgFAAgDACQgFABgCADIgFAGQgCADgBAEIAsAAIAAAAgAErAsQgGgDgGgGQgGgFgDgHQgCgHAAgIQAAgIACgGQADgHAGgFQAGgGAGgCQAIgDAHAAQAIAAAIADQAGACAGAGQAFAFADAHQADAGAAAIQAAAIgDAHQgDAHgFAFQgGAGgGADQgIADgIAAQgHAAgIgDgAEwgQQgEACgEAEQgDAEgDAFQgCAEAAAFQAAAGACAFQADAFADADQAEAEAEACQAFACAFAAQAGAAAEgCQAFgCAEgEQAEgDACgFQABgFAAgGQAAgFgBgEQgCgFgEgEQgEgEgFgCQgEgCgGAAQgFAAgFACgABwAsQgHgDgFgFQgFgFgCgHQgDgIAAgIQAAgIADgHQACgHAFgFQAFgFAHgDQAGgCAIAAQAIAAAGACQAHADAEAFQAFAFACAGQACAIAAAHIAAADIg4AAIAAABQAAAGACAEQABAFADAEQADADAFACQAEACAFAAQAHAAAHgEQAFgEAFgIIAJAGIgHAJQgDADgEADIgJAEIgLABQgHAAgHgDgACTAAQAAgEgCgEIgEgGQgDgCgEgBQgEgCgFAAQgEAAgEACQgDABgEADIgEAGQgCADAAAEIArAAIAAAAgAArAuIgIgDIgGgFQgDgCgCgEIAKgHQADAFAFADQAFADAFAAQAGAAAEgDQAEgDAAgFQAAgEgDgCQgDgDgFgCIgMgEIgJgEIgGgGQgCgDAAgFQAAgEACgEIAGgHQADgDAFgCQAEgBAGAAIAJABIAHACIAFAFIAFAGIgKAGQgCgFgFgDQgEgCgGAAQgFAAgDADQgEADAAAEQAAAFAFADIAOAEIAJADIAGAFIAEAFIABAIIgBAJQgCAEgEADIgIAFQgFACgGAAIgJgBgAgVAuIgIgDIgGgFQgDgCgCgEIALgHQADAFAEADQAEADAHAAQAGAAAEgDQACgDAAgFQAAgEgCgCQgCgDgGgCIgMgEIgJgEIgGgGQgBgDAAgFQAAgEABgEIAGgHQADgDAFgCQAFgBAFAAIAJABIAGACIAFAFIAFAGIgLAGQgBgFgEgDQgEgCgGAAQgFAAgDADQgEADAAAEQAAAFAFADIANAEIAIADIAHAFIAEAFIABAIQAAAFgCAEQgBAEgEADIgHAFQgFACgGAAIgJgBgAhjAsQgHgDgEgFQgFgFgDgHQgCgIAAgIQAAgIACgHQADgHAFgFQAEgFAGgDQAHgCAIAAQAIAAAGACQAHADAEAFQAEAFADAGQACAIAAAHIAAADIg5AAIAAABQAAAGACAEQACAFAEAEQADADAEACQAEACAGAAQAGAAAGgEQAGgEAEgIIAKAGIgGAJQgEADgEADIgJAEIgKABQgJAAgGgDgAhAAAQAAgEgBgEIgFgGQgDgCgEgBQgDgCgFAAQgFAAgDACQgFABgCADIgFAGQgCADgBAEIAsAAIAAAAgAj3AsQgGgDgFgFQgEgFgDgHQgDgHAAgJQAAgIADgHQADgHAEgFQAEgFAHgDQAGgCAHAAIAIABIAIADIAFAFIAFAHIAAg/IAMAAIAAB4IgMAAIAAgNIgEAHIgGAFIgIADIgHABQgIAAgGgDgAjxgPQgFABgDADQgCAEgCAEQgCAEABAGQgBAGACAGQACAFADAEQADADAEACQAEACAFAAQAGAAAEgCQAFgCADgDQADgDACgFQABgFAAgHQAAgGgBgEQgCgEgDgEQgDgDgFgCQgEgCgGAAQgFAAgEACgAnfAsQgHgDgEgFQgFgFgCgHQgDgHAAgJQAAgIADgHQACgHAFgFQAEgFAGgDQAGgCAHAAIAJABIAHADIAGAFIAFAHIAAgOIAMAAIAABHIgMAAIAAgNIgEAHIgHAFIgHADIgIABQgHAAgGgDgAnagPQgEABgDAEQgDADgCAFQgBADAAAHQAAAGABAFQACAFAEAEQACADAEACQAFACAGAAQAFAAAFgCQAEgCADgDQADgDABgFQACgFAAgGQAAgGgCgEQgBgFgEgEQgDgDgEgCQgEgCgFAAQgGAAgFACgArCAuIgJgDIgIgFIgHgIIAKgLIAFAHIAFAFIAHADIAIABQAGAAAFgCQAFgCAEgEQAEgEACgFQACgFAAgHQAAgGgCgEQgCgFgEgEQgEgEgFgCQgFgCgHAAQgHAAgGADQgGACgGAEIgCgBIANg4IAzAAIAAAMIgpAAIgHAeQAEgDAEgBIAJgBQAJAAAGADQAIADAEAFQAFAEACAHQADAHAAAIQAAAJgDAIQgDAIgGAFQgFAGgHADQgJADgJAAIgLgBgAt2AuIgIgDIgHgFIgGgHIgEgIIgEgKQgCgIgBgRQAAgJADgQQACgHAGgLIAGgHIAHgFIAIgDIAIgBIAJABIAHADIAHAFIAGAHQADADABAFIAEAKQADAQAAAJQgBARgCAIIgEAKIgEAIIgGAHIgHAFIgHADIgIABIgJgBgAt5g5QgEAEgEAGQgDAGgBAJQgCAJAAALQAAAMACAIQABAJADAGQAEAGAEADQAGAEAFAAQAGAAAFgDQAFgDAEgHQADgGABgJQACgIAAgLQAAgMgCgJQgBgJgDgHQgEgGgFgDQgFgDgGAAQgFAAgGADgAPIAsIAAhHIALAAIAAAPIAEgIIAGgFIAGgDIAIgBQAEAAAEABIgFALIgHgBQgEAAgFACQgDABgCAEQgDADgBAGIgBALIAAAjgAIvAsIAAgqQAAgFgBgEQgBgEgCgCQgDgDgEgBQgDgCgFAAQgFAAgFACQgEACgDAEQgDADgBAFIAAAKIAAAlIgNAAIAAh4IANAAIAAA8QAEgHAGgDQAHgDAJAAQAGAAAFABIAIAFQAEAEABAEQADAFAAAGIAAAwgAHTAsIAAg9IgMAAIAAgKIAMAAIAAgdIAMAAIAAAdIAOAAIAAAKIgOAAIAAA9gAF4AsIAAg9IgOAAIAAgKIAOAAIAAgUIAAgOQABgGACgEQADgDAEgCQAEgCAGAAQAGAAAFACIAAAMQgFgCgFAAQgDAAgCABQgBAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgBADAAAMIAAATIATAAIAAAKIgTAAIAAA9gACyAsIAAhHIALAAIAAAPIAGgIIAFgFIAGgDIAIgBQAEAAAEABIgFALIgHgBQgEAAgEACQgEABgCAEQgDADgBAGIgBALIAAAjgAirAsIAAhHIALAAIAAAPIAGgIIAFgFIAGgDIAHgBQAFAAAEABIgFALIgHgBQgEAAgEACQgEABgDAEQgCADgBAGIgBALIAAAjgAltAsIAAhHIALAAIAAAPIAFgIIAGgFIAGgDIAHgBQAEAAAEABIgEALIgIgBQgEAAgEACQgEABgCAEQgCADgCAGIAAALIAAAjgAmTAsIAAhHIANAAIAABHgAoTAsIAAgqQABgFgCgEQgBgEgCgCQgDgDgDgBQgEgCgFAAQgFAAgEACQgFACgDAEQgDADgBAFIAAAKIAAAlIgNAAIAAh4IANAAIAAA8QAEgHAHgDQAGgDAIAAQAHAAAFABIAIAFQAEAEABAEQACAFAAAGIAAAwgAsTAsIAAhlIgYAAIAIgMIAdAAIAABxgAvyAsIAYgdIAZgeIAHgMQADgGAAgFQAAgFgCgDQgBgEgDgDIgHgEQgFgBgEAAQgGAAgEABQgEACgDADQgDADgBAEQgCAFAAAFIAAACIgNAAIAAgDQAAgJACgGQADgGAEgFQAFgEAHgCQAGgDAJAAQAIAAAHACQAHADAEAEQAFAEACAGQACAGABAHQAAAGgCAGIgGAMIgJANIgeAhIArAAIAAANgAmTg3QgDgCAAgEQAAgEADgDQACgCAEAAQAEAAADADQACACAAAEQAAAEgCACQgDADgEAAQgEAAgCgDg");
	this.shape.setTransform(-277,250.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// dmputext.svg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACMBVQgKgEgIgIQgIgIgEgKQgEgKAAgLQAAgMAEgKQAEgKAIgHQAIgIAKgEQAKgEAMAAQALAAAKAEQAKAFAIAIQAIAGAEAKQAFAKAAAMQAAALgFAKQgEAKgIAIQgIAIgKAEQgKAEgLAAQgMAAgKgEgACTgBQgHACgFAFQgFAFgDAHQgCAIAAAIQAAAIACAHQADAHAFAFQAGAGAGADQAHADAIAAQAHAAAHgDQAHgDAFgGQAFgFADgHQADgHAAgIQAAgIgDgIQgDgHgFgFQgFgFgHgCQgHgDgHAAQgIAAgHADgAIQBVIAAhmIASAAIAABmgAGeBVIA7hXIg4AAIAAgPIBXAAIg7BWIA6AAIAAAQgAF2BVIAAhmIARAAIAABmgAFABVIAAg9QAAgIgBgFQgCgGgDgEQgEgDgFgCQgFgCgHAAQgIAAgGADQgHADgEAEQgEAFgBAIIgBAPIAAA1IgRAAIAAhmIARAAIAAAQQAHgKAJgFQAJgFAMAAQAJAAAIADQAHACAFAFQAFAFACAGQADAGAAAJIAABGgABKBVIhKhYIAABYIgSAAIAAikIASAAIAABJIBFhJIAXAAIhGBKIBNBagAiMBVIAAg9QAAgIgCgFQgCgGgDgEQgDgDgFgCQgFgCgHAAQgIAAgHADQgGADgEAEQgEAFgCAIIAAAPIAAA1IgSAAIAAhmIARAAIAAAQQAHgKAJgFQAKgFAMAAQAJAAAHADQAHACAFAFQAFAFADAGQADAGAAAJIAABGgAkOBVIAAhmIARAAIAABmgAk5BVIg1g2IAAA2IgSAAIAAitIASAAIAAB1IAxguIAYAAIg0AuIA4A4gAmkBVIgWgzIhAAAIgVAzIgWAAIBLiqIBLCqgAnAASIgag8IgaA8IA0AAgAIQg5QgEgEAAgGQAAgFAEgEQADgDAGAAQAFAAAEADQAEAEAAAGQAAAFgEAEQgEADgFAAQgGAAgDgDgAF1g5QgEgEAAgGQAAgFAEgEQAEgDAFAAQAGAAADADQAEAEAAAGQAAAFgEAEQgDADgGAAQgFAAgEgDgAkPg5QgEgEAAgGQAAgFAEgEQAEgDAFAAQAGAAADADQAEAEAAAGQAAAFgEAEQgDADgGAAQgFAAgEgDg");
	this.shape_1.setTransform(-275.3,216.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Text, new cjs.Rectangle(-378.1,207.9,202.2,50.5), null);


(lib.Strap = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ao0BLIAAiVIRpAAIAACVg");
	mask.setTransform(72.6,34.2);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape.setTransform(119.3,33,0.521,0.521);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQgBgVAQgQIABgBIgBAAQAQgQAXAAQAWAAARAQQAQAQAAAWQAAAXgQAPIAAABQgQAQgXAAQgWAAgQgQgAgYgbQgLALgBAQIAAAAQgBAQALALQAKALAQABIAAAAQAQABALgLQAMgLABgQQABgPgLgMQgLgLgQgBIgCAAQgOAAgLAKg");
	this.shape_1.setTransform(112.7,33.1,0.521,0.521);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("AgIBSIAAhlIARAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_2.setTransform(107.8,31.5,0.521,0.521);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("AgIBIIAAhXIgTAAIAAgPIATAAIAAgoIAQAAIAAAoIATAAIAAAPIgTAAIAABXg");
	this.shape_3.setTransform(104.8,32.1,0.521,0.521);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_4.setTransform(101.8,31.5,0.521,0.521);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AglBJQgNgPAAgYQAAgZANgOQAOgPAVAAQALgBAKAHQAKAGAFAKIAAhZIARAAIAACrIgQAAIAAgSQgFAKgLAGQgKAGgKAAQgWAAgOgPgAgXAGQgJAJAAARQAAATAJAKQAJALAOAAQAQAAAJgKQAKgKAAgSQAAgSgKgKQgJgJgQAAQgOAAgJAJg");
	this.shape_5.setTransform(96.8,31.4,0.521,0.521);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AgqBSIAAiiIBVAAIAAASIhBAAIAAAuIBBAAIAAARIhBAAIAAA/IBBAAIAAASg");
	this.shape_6.setTransform(90.7,31.5,0.521,0.521);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AgIBWIAAirIARAAIAACrg");
	this.shape_7.setTransform(83,31.3,0.521,0.521);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("AglAoQgNgPAAgZQAAgYANgPQANgPAWAAQALAAAKAGQAKAGAFALIAAgTIARAAIAABlIgQAAIAAgTQgFALgLAGQgKAGgKAAQgWAAgOgPgAgXgbQgJAKAAARQAAARAJAKQAJALAPAAQAQAAAJgKQAJgKAAgRQAAgRgKgKQgKgKgPAAQgPAAgIAJg");
	this.shape_8.setTransform(78,33.1,0.521,0.521);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape_9.setTransform(71.5,33,0.521,0.521);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_10.setTransform(64.7,33.1,0.521,0.521);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_11.setTransform(59.9,31.5,0.521,0.521);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#999999").s().p("AgUAyQgMgGgFgLIANgJQAEAIAHAEQAIAFAGgBQAJAAAGgEQAEgFAAgGQAAgGgDgEQgDgCgJgDQgWgJgHgDQgKgHAAgNQAAgOAJgIQALgJAOAAQAMgCAKAGQAKAGAFAKIgOAJQgDgHgHgEQgGgEgHAAQgGAAgFAEQgFAEgBAGIAAABQABAHAGAEQADACAQAEQAPAFAHAGQAHAHAAALQABAPgLAJQgKAJgRAAIgCAAQgLAAgIgFg");
	this.shape_12.setTransform(56.1,33.1,0.521,0.521);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#999999").s().p("AgVAyQgLgGgGgLIAPgJQAHARASgBQAIAAAGgEQAFgFAAgGQAAgGgEgEQgEgCgIgDQgXgJgFgDQgLgHAAgNQAAgOAKgIQAKgJAPAAQALgCAKAGQAKAGAFAKIgOAJQgHgQgQABQgFgBgGAEQgEAEgBAHIAAABQgBAHAHAEQADACAQAEQAPAFAHAGQAHAHABALQAAAPgKAJQgLAJgQAAIgDAAQgKAAgKgFg");
	this.shape_13.setTransform(51.2,33.1,0.521,0.521);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#999999").s().p("AACA3QgWAAgOgPQgPgQAAgYQAAgYAOgPQAOgPAWAAQAWAAANAPQAOAOAAAZIAAACIhQAAIAAACQgBAOAJALQAIALAOABIADAAQAXgBAKgVIANAJQgHANgNAHQgLAHgOAAIgCAAgAgUgfQgJAIgBAMIA9AAQAAgLgIgJQgIgIgMAAIgDAAIgBAAQgLAAgIAIg");
	this.shape_14.setTransform(45.8,33.2,0.521,0.521);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#999999").s().p("AgMBXIAAhXIgTAAIAAgOIATAAIAAgdQABgYAFgJQAGgKARAAQAGAAAJACIAAASQgFgDgJAAQgJAAgDAHQgBAEAAARIAAAcIAbAAIAAANIgbAAIAABXg");
	this.shape_15.setTransform(41.1,31.2,0.521,0.521);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_16.setTransform(35.9,33.1,0.521,0.521);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#999999").s().p("AgeA1IAAhmIAQAAIAAAWQAHgNAHgGQAHgGAMAAQAGAAAGACIgGAQIgLgCQgbAAAAAnIAAAyg");
	this.shape_17.setTransform(30.9,33.1,0.521,0.521);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#999999").s().p("AgtBSIAAiiIAiAAQAdgBALAJQAPANACAUQABAVgNAOIgFAEQgHAFgLADIgWABIgPAAIAABJgAgagIIAKAAQAWAAAJgFQAKgGAAgPQAAgQgKgHQgKgGgVABIgKAAg");
	this.shape_18.setTransform(25.9,31.5,0.521,0.521);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9D9D9C").s().p("AnWCpIAAioQAAglAagbQAbgbAlAAIAHAAQAlABAZAbQAZAbgBAkQgBAmgbAaQgcAbgmgBIgxAAIAABOgAmhgjQgOAQAAAUIAAAzIAzAAQAWAAAPgPQAQgQgBgVQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgUgQgOQgPgOgVAAIgBAAQgVABgPAQgAD1BAQgbgaABgmQAAgkAagbQAbgbAlAAQAmAAAbAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgmAAgbgbgAESglQgPAPgBAVQAAAVAPARQAPAQAWABIABAAQAWgBAPgQQAPgPgBgWIAAAAQAAgVgPgQQgPgQgWAAQgVABgPAPgAjyBBQgbgagBgmQAAglAagbQAbgbAlAAQAmgBAbAbQAbAaABAmIgCANIiMAAQAEASAOANQAPAMASgBQAdAAAZgSIAWAcQghAagpAAIgBAAIgCAAQglAAgagagAjRgsQgNAKgGARIBiAAQgFgQgNgLQgNgKgRAAQgRAAgOAKgAMNBbQgmAAgagbQgbgaAAglIABgBQgBgkAagbQAagbAlAAIACAAQAhgBAZAXIgXAaQgQgMgUABQgWACgPAQQgOARABAVQABAUAOAOQAOAPAVACQAUACAPgNIAZAZQgYAXggAAIgDAAgAAxA/IAVgbQAaARAgADQAgAAAAgRQAAgIgRgHIglgLQg2gPAAgjQAAgWATgPQAUgPAfAAQAmAAAfATIgUAbQgWgLgagBQgdAAAAARQAAAIA1AQQA1APAAAiQAAAbgYAPQgUANgdABQgrgCgjgagApGBbQglAAgZgZQgbgaAAgsIAAhTIAoAAIAABTQAAAbAPAPQAOAOAVABQAVgBAOgOQAPgPAAgbIAAhTIAoAAIAABTQAAArgbAaQgZAZglABgAtHA/IAWgbQAZARAhADQAfAAAAgRQAAgIgRgHIglgLQg1gPAAgjQAAgWATgPQAUgPAfAAQAlAAAgATIgUAbQgXgLgagBQgdAAAAARQAAAHARAGIAlALQA1APAAAiQAAAbgYAPQgVANgdABQgqgCgkgagAGmgHQABgkAcgaQAbgZAlABQAkABAaAbQAZAbgBAlIAABYIgoAAIAAhWQABgFgBgGQgCgUgRgNQgQgNgVACQgUADgNAQQgNAQACAUIAABWIgnABgAhDBYIAAhZQABgmAbgZQAbgbAlABIAJAAIAAAlQgHgBgIACQguAIAAAwIAABUgAJ1BXIAAiuIAoAAIAACugAKKh6QgJAAgHgGQgHgIAAgJQAAgJAHgHQAHgHAJAAQAKAAAGAHQAHAHAAAJQAAAJgGAIQgHAGgJAAg");
	this.shape_19.setTransform(100.4,9.4,0.521,0.521);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#1D1D1B").s().p("AgiCEQgbgHgVgRIAYggQAUAOAaADQAgABAOgcQAIgRAAgWQgTARgXAAQgkAAgbgaQgbgZAAglIAAhaIAwAAIAABZQAAASAMAMQANANARAAQARAAANgNQANgMAAgSIAAhZIAwAAIAABZQAABSgHAdQgPA2gzAMQgNADgNAAQgNAAgNgDg");
	this.shape_20.setTransform(15.5,11.8,0.521,0.521);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#1D1D1B").s().p("AgJBbQglgGgdgWIAXgfQALAIASAGQAXAHAQgFQALgCACgHQACgGgHgFIgggKQgbgHgNgIQgQgIgFgRQgFgRAIgRQANgYAfgIQAQgDAMACQAhABAdATIgXAfQgdgNgfAEQgIACgCAFQgCAGAGADIAAAAQAFAFAZAHQAcAHAMAGQAcAOgBAcQgBASgJALQgRAVgfAFg");
	this.shape_21.setTransform(25.3,9.4,0.521,0.521);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#1D1D1B").s().p("AArBZIAAhXQAAgRgNgMQgMgNgSAAQgRAAgNANQgMAMAAARIAABXIgvAAIAAhXQgBglAbgaQAbgbAkAAQAlAAAbAbQAaAaABAlIAABXg");
	this.shape_22.setTransform(45.2,9.3,0.521,0.521);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#1D1D1B").s().p("Ag/BAQgbgaAAgmQAAgkAbgbQAagaAlgBQAmAAAaAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgkAAgbgbgAgdgdQgNAMAAARQAAASAMANQANANARAAQASAAANgNQAMgNAAgSQAAgRgMgMQgNgNgSAAQgRAAgMANg");
	this.shape_23.setTransform(34.7,9.3,0.521,0.521);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#1D1D1B").s().p("Ag/BtQgbgbAAglQAAgmAagaQAbgaAlgBIArAAIAAhYIAwAAIAACyQgBAmgaAbQgbAaglAAQglAAgagagAgeAOQgMAMAAASQAAASAMANQANAMARAAQARAAANgMQANgNAAgSIgBgrIgqAAQgRAAgNANg");
	this.shape_24.setTransform(4.7,7.1,0.521,0.521);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Strap, new cjs.Rectangle(16.2,26.6,112.9,9.4), null);


(lib.ProductShot_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ProductShot();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ProductShot_1, new cjs.Rectangle(0,0,300,600), null);


(lib.NewerQuote = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArIEFIgiBNIgthqIATAAIAbBEIAfhIIACAAIAfBIIAbhEIATAAIgsBqgAwrEFIghBNIgthqIATAAIAbBEIAfhIIADAAIAdBIIAbhEIAUAAIgtBqgACvFQQgXAAgOgPQgOgPAAgYQAAgYAOgPQAOgPAWAAQAWAAANAOQANAOAAAZIAAAEIhQAAIAAABQAAAQAKAKQAJAKAPAAQATAAANgWIAOAJQgIANgMAIQgLAGgNAAIgDAAgADMEPQgCgcgdAAQgMgBgJAJQgJAIgBAMIA+AAIAAAAgAJhFAQgQgQAAgWIAAAAQgBgWARgQQARgQAWAAQAWgBARARIAAAAQAQAQgBAWQAAAXgPAPQgQAQgXAAIgCAAQgVAAgQgQgAJwEBQgMAKgBAPIAAABQAAAPALALQALALAPAAQAPAAAKgKQAKgKABgOQABgQgLgLQgJgLgQAAIgBAAQgOAAgKAJgAHjFAQgPgPgBgXQABgXAPgPQARgRAWABQAWAAARAQIABABQAPAQAAAWQgBAWgPAPQgQAQgXAAIgDAAQgUAAgQgQgAHyEBQgMAKgBAPIABAAIgBABQABAPAKALQALALAPAAQAPAAAKgKQALgKAAgOQACgQgLgLQgKgLgQAAIgBAAQgOAAgKAJgApFFQQgWAAgNgOQgNgPAAgZQAAgZANgOQANgPAVAAQAMAAAKAGQAKAGAFALIAAgTIARAAIAABkIgQAAIAAgSQgGALgKAGQgJAFgKAAIgCAAgApbD/QgIAJAAARQAAAmAiAAQAPAAAJgJQAIgKABgRQAAgRgKgLQgJgKgPAAQgPAAgKAKgAQgFPQgGAAgDgDQgEgEAAgFQAAgFAEgEQADgEAGAAQAFAAAEAEQADAEAAAFQAAAFgDAEQgEADgEAAIgBAAgAPfFMIAAhWIgSAAIAAgOIASAAIAAgpIASAAIAAApIASAAIAAAOIgSAAIAABWgAOrFMIAAhkIARAAIAABkgAOCFMIgzg1IgBA1IgRAAIAAiqIASAAIAABzIAxgtIAWAAIgyAuIA3A2gALXFMIAAiqIARAAIAACqgAGoFMIAAhWIgSAAIAAgOIASAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAABWgAEmFMIAAhkIAPAAIAAAVQAHgNAHgGQAJgGALAAQAHAAAFACIgHAQQgFgCgFAAQgbAAAAAnIAAAxgAD2FMIAAhkIAQAAIAABkgABUFMIAAg7QAAgegbAAQgPAAgJALQgHAHAAATIAAA0IgRAAIAAiqIARAAIAABVQANgUAYABQARAAALAKQAKAJAAARIAABEgAgqFMIAAhWIgTAAIAAgOIATAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAABWgAiRFMIAAg7QAAgegbAAQgPAAgKALQgFAHAAATIAAA0IgRAAIAAhkIARAAIAAAPQAGgJAJgFQAKgFAMAAQARAAAKAKQAKAJAAARIAABEgAkMFMIAAhkIARAAIAABkgAl1FMIAAhWIgSAAIAAgOIASAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAABWgAmoFMIAAg7QAAgegbAAQgOAAgKALQgGAHABATIAAA0IgSAAIAAhkIASAAIAAAPQAFgJAKgFQAKgFALAAQARAAALAKQAKAJgBARIAABEgAtrFMIAAiqIARAAIAACqgAucFMIAAiqIARAAIAACqgAvNFMIAAhkIARAAIAABkgARSDjIAUg7IAUAGIgcA7gAQrDjIAUg7IATAGIgbA7gAO0DEQgGAAgDgEQgEgDAAgGQAAgFAEgEQADgDAGAAQAFAAAEADQADAEAAAFQAAAGgDADQgEAEgEAAIgBAAgAD+DEQgFAAgEgEQgDgDgBgGQABgFADgEQAEgDAFAAQAFAAAEADQADAEABAFQgBAGgDADQgEAEgEAAIgBAAgAkDDEQgFAAgEgEQgDgDgBgGQABgFADgEQAEgDAFAAQAFAAAEADQADAEABAFQgBAGgDADQgEAEgEAAIgBAAgAvEDEQgGAAgDgEQgEgEABgFQgBgFAEgEQAEgDAFAAQAFAAAEADQADAEAAAFQAAAGgEADQgDAEgEAAIgBAAgAKfCDIAbg7IgnhZIAUAAIAdBHIAfhHIATAAIhECUgAFuCDIAcg7IgnhZIAUAAIAcBHIAghHIATAAIhECUgAl2CDIAcg7IgohZIAUAAIAdBHIAfhHIATAAIhDCUgAA8gRIATAAIAeBFIAfhFIAUAAIgyBqgADXBWQgXAAgOgPQgOgPAAgYQAAgYAOgOQAOgPAWAAQAWAAAOAOQAMANAAAZIAAADIhPAAIAAACQgBAQAKAKQAKAKAOAAQAUAAANgWIANAJQgHANgNAIQgLAGgNAAIgDAAgAD0AVQAAgOgJgHQgIgGgOAAQgMgBgIAIQgJAIgBAMIA9AAIAAAAgAAIBWQgWAAgOgPQgPgPAAgYQAAgYAOgOQAPgPAVAAQAWAAANAOQANANAAAZIAAAEIhOAAIAAABQgBAQAKAKQAKAKANAAQATAAAOgWIAMAJQgGANgNAIQgLAGgNAAIgDAAgAAlAVQgCgbgdAAQgLgBgJAIQgJAIAAAMIA8AAIAAAAgAjoBWQgXAAgOgPQgOgPAAgYQAAgYANgOQAPgPAWAAQAWAAANAOQANANAAAZIAAAEIhPAAIAAABQAAAQAJAKQAKAKAOAAQATAAANgWIAOAJQgIANgMAIQgLAGgNAAIgDAAgAjLAVQgCgbgdAAQgMgBgJAIQgIAIgBAMIA9AAIAAAAgAtGBWQgXAAgNgOQgNgPAAgZQAAgZANgNQANgPAWAAQALAAAKAGQAKAGAGAKIAAgSIARAAIAABjIgRAAIAAgSQgFAKgLAGQgIAGgLAAIgBAAgAtcAFQgJAJABARQgBAmAiAAQAPAAAJgJQAIgKABgRQgBgRgJgLQgJgJgPAAQgPAAgJAJgANdBBIAOgKQADAIAIAEQAHAFAHgBQAJAAAGgEQAEgEAAgHQAAgKgPgFQgXgIgHgEQgKgHAAgOQAAgMAKgIQAKgJAPAAQAcAAAIAUIgNAIQgIgPgQABQgHAAgEAFQgGADAAAGQABAHAGAEIATAHQAQAEAHAHQAGAHAAAMQAAAOgKAIQgKAJgQAAQgcAAgLgVgAH8BBIAPgKQAHARASgBQAJAAAGgEQAEgEAAgHQAAgJgPgGQgYgIgGgEQgKgHAAgOQAAgMAJgIQALgJAPAAQAcAAAIAUIgNAIQgHgPgRABQgHAAgEAEQgGAEAAAGQABAHAGAEIATAHQAQAFAGAGQAHAHAAAMQABAOgLAIQgKAJgRAAQgbAAgMgVgAo9BIQgNgPgBgZQABgZANgNQAMgPAWAAQAMAAAKAGQAJAGAGAKIAAhYIARAAIAACpIgRAAIAAgSQgFAKgKAGQgJAGgNAAQgVAAgNgOgAowAEQgIAKAAAQQAAATAJAKQAIALAQAAQAPAAAJgKQAJgKAAgSQAAgRgKgKQgIgJgQAAQgPAAgJAIgAPHBSIAAhVIgTAAIAAgOIATAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAABVgAM2BSIAAhjIARAAIAABjgAMFBSIAAipIARAAIAACpgAJnBSIAAhVIgTAAIAAgOIATAAIAAgpIAQAAIAAApIAUAAIAAAOIgUAAIAABVgAEeBSIAAhjIAPAAIAAAUQAHgMAHgGQAJgGALAAQAHAAAFACIgGAQIgLgCQgbAAAAAmIAAAxgAiiBSIAAhjIAQAAIAAAUQAMgYAWAAQAGAAAGACIgHAQIgKgCQgbAAAAAmIAAAxgAnGBSIAAhjIAPAAIAAAUQAHgMAHgGQAIgGALAAQAIAAAEACIgFAQIgLgCQgbAAAAAmIAAAxgArCBSIAAhjIAOAAIAAAUQANgYAVAAQAIAAAEACIgFAQIgLgCQgbAAAAAmIAAAxgArzBSIAAhjIARAAIAABjgAugBSIAAg7QAAgdgbAAQgOAAgKAKQgGAHAAATIAAA0IgRAAIAAipIARAAIAABVQAGgJAKgFQAKgFALAAQARAAALAKQAKAJgBAQIAABEgAM/g1QgGAAgDgEQgEgDAAgGQAAgFAEgEQADgDAGAAQAFAAAEADQADAEAAAFQAAAGgDADQgEAEgEAAIgBAAgArrg1QgEAAgFgEQgDgDAAgGQAAgFADgEQAFgDAEAAQAGAAADADQAFAEgBAFQAAAGgEADQgDAEgEAAIgCAAgAlfkLIATAAIAfBGIAehGIATAAIgxBqgApckdIgqB8Ig+inIAVAAIAoB3IArh9IArB9IAoh3IAWAAIg/CngAGzijQgXAAgPgPQgOgPABgYQgBgYAOgPQAPgPAVAAQAXAAANAOQANAOAAAZIAAADIhPAAIAAACQgBAQAKAKQAJAKAPAAQATAAANgWIAOAJQgIANgMAIQgLAGgNAAIgDAAgAHQjkQgBgOgIgHQgJgHgNAAQgMgBgJAJQgJAIAAAMIA9AAIAAAAgACLijQgXAAgOgPQgOgPAAgYQAAgYAOgPQAOgPAWAAQAXAAANAOQANAOgBAZIAAADIhPAAIAAACQAAAQAJAKQAJAKAPAAQAVAAALgWIAOAJQgHANgMAIQgMAGgNAAIgDAAgACojkQgBgOgIgHQgIgHgNAAQgMgBgKAJQgIAIgBAMIA9AAIAAAAgAjEijQgWAAgPgPQgOgPAAgYQAAgYAOgPQAPgPAVAAQAWAAANAOQAOAOAAAZIAAADIhQAAIAAACQAAAQAKAKQAJAKAPAAQATAAANgWIANAJQgHANgNAIQgLAGgMAAIgEAAgAimjkQgDgcgdAAQgLgBgJAJQgJAIgBAMIA+AAIAAAAgAnEijQgXAAgOgPQgOgPgBgYQABgYAOgPQANgPAXAAQAWAAANAOQANAOAAAZIAAADIhQAAIAAACQAAAQAKAKQAJAKAOAAQAUAAAOgWIAMAJQgGANgNAIQgLAGgNAAIgDAAgAmojkQAAgOgJgHQgHgHgOAAQgMgBgJAJQgJAIgBAMIA9AAIAAAAgAgeijQgXAAgOgOQgOgPgBgYQABgYAPgQQAOgPAXAAQAQAAAOAHIAAASQgMgIgPAAQgQAAgLAKQgKALAAARIgBACQABAPAKAKQALAKAPAAQAQAAAOgMIAAAUQgNAIgQAAIgEAAgALVijQgVAAgOgOQgNgPAAgZQAAgZANgOQANgPAVAAQAMAAAKAGQAKAGAFALIAAgTIARAAIAABkIgQAAIAAgSQgGAKgKAGQgJAGgKAAIgCAAgALAj0QgJAJAAARQAAATAJAJQAJAKAPAAQAQAAAJgJQAJgKAAgRQAAgRgKgLQgJgKgPAAQgPAAgJAKgAIjijQgWAAgNgOQgNgPAAgZQAAgZANgOQANgPAVAAQANAAAJAGQAKAGAFALIAAhZIARAAIAACqIgQAAIAAgSQgFAKgKAGQgKAGgKAAIgCAAgAIPj1QgKAKABAQQgBATAKAKQAIALAPAAQAPAAAJgKQAKgKAAgSQAAgQgKgLQgJgKgPAAQgPAAgIAJgAD7ijQgVAAgNgOQgNgPAAgZQgBgZANgOQANgPAWAAQAMAAAKAGQAJAGAFALIAAgTIASAAIAABkIgRAAIAAgSQgFAKgKAGQgJAGgLAAIgCAAgADnj0QgJAJAAARQAAAmAiAAQAPAAAIgJQAJgKAAgRQAAgRgKgLQgIgKgPAAQgQAAgIAKgAFUinIAAhWIgTAAIAAgOIATAAIAAgpIARAAIAAApIASAAIAAAOIgSAAIAABWgAAXinIAAhkIAPAAIAAAVQAHgNAHgGQAJgGALAAQAGAAAGACIgGAQQgGgCgFAAQgbAAAAAnIAAAxgAmJkQIAVg7IATAGIgbA7gAr5kRIAbg6IAMAFIgUA8gAshkRIAbg6IANAFIgVA8g");
	this.shape.setTransform(114.6,33.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.NewerQuote, new cjs.Rectangle(0,0,229.1,67.7), null);


(lib.NEW_CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjGCmIAAjiIAZAAIAAAdQAIgQAPgJQAPgJASAAQAhAAATAWQAVAWAAAlQAAAmgVAWQgTAWggAAQgTABgPgKQgOgJgIgQIAABmgAifgZQgOAPAAAaQAAAaAPAPQAOAQAXAAQAWAAAOgOQANgPAAgZQAAgbgOgQQgMgQgYAAQgXAAgOAPgAG7BiQgjAAgVgXQgVgXgBglQABgjAVgWQAVgXAiAAQAhAAAUAVQAUAWAAAkIAAAFIh5AAIAAADQAAAYAOAPQAOAPAWAAQAfAAATghIAUAOQgKATgTAMQgSAKgUAAIgEAAgAHngBQgDgpgrAAQgTgBgNAMQgOAMgBASIBdAAIAAAAgABUBKQgZgXAAgjQAAgiAZgXQAYgZAjABQAhgBAZAZIABABQAXAYABAhQgBAhgYAYQgYAXgiABQgjAAgYgYgABpgVQgRAPgBAWIAAABQAAAXAQARQARAQAXABQAVgBARgPQAQgPABgWQABgWgQgRQgQgRgWgBIgDAAQgWAAgPAPgAEHBcIAAiXIAXAAIAAAfQAKgTAMgJQAMgJARAAQAKAAAIADIgJAYIgQgDQgpAAAAA6IAABLgAgFBcIAAkBIAZAAIAAEBgAj+BcIgpg7IgqA7IggAAIA7hPIg5hIIAgAAIAoA2IAog2IAhAAIg6BIIA7BPgAoCBcIAAjzICBAAIAAAbIhjAAIAABGIBjAAIAAAaIhjAAIAABdIBjAAIAAAbg");
	this.shape.setTransform(57.9,18.7,0.5,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C4398D").s().p("AyvFeIAAq7MAlfAAAIAAK7g");
	this.shape_1.setTransform(60,17.5,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.NEW_CTA, new cjs.Rectangle(0,0,120,35), null);


(lib.Logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AriB/IAAj+IXFAAIAAD+g");
	mask.setTransform(72.8,7.5);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape.setTransform(119.3,33,0.521,0.521);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQgBgVAQgQIABgBIgBAAQAQgQAXAAQAWAAARAQQAQAQAAAWQAAAXgQAPIAAABQgQAQgXAAQgWAAgQgQgAgYgbQgLALgBAQIAAAAQgBAQALALQAKALAQABIAAAAQAQABALgLQAMgLABgQQABgPgLgMQgLgLgQgBIgCAAQgOAAgLAKg");
	this.shape_1.setTransform(112.7,33.1,0.521,0.521);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("AgIBSIAAhlIARAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_2.setTransform(107.8,31.5,0.521,0.521);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("AgIBIIAAhXIgTAAIAAgPIATAAIAAgoIAQAAIAAAoIATAAIAAAPIgTAAIAABXg");
	this.shape_3.setTransform(104.8,32.1,0.521,0.521);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_4.setTransform(101.8,31.5,0.521,0.521);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AglBJQgNgPAAgYQAAgZANgOQAOgPAVAAQALgBAKAHQAKAGAFAKIAAhZIARAAIAACrIgQAAIAAgSQgFAKgLAGQgKAGgKAAQgWAAgOgPgAgXAGQgJAJAAARQAAATAJAKQAJALAOAAQAQAAAJgKQAKgKAAgSQAAgSgKgKQgJgJgQAAQgOAAgJAJg");
	this.shape_5.setTransform(96.8,31.4,0.521,0.521);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AgqBSIAAiiIBVAAIAAASIhBAAIAAAuIBBAAIAAARIhBAAIAAA/IBBAAIAAASg");
	this.shape_6.setTransform(90.7,31.5,0.521,0.521);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AgIBWIAAirIARAAIAACrg");
	this.shape_7.setTransform(83,31.3,0.521,0.521);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("AglAoQgNgPAAgZQAAgYANgPQANgPAWAAQALAAAKAGQAKAGAFALIAAgTIARAAIAABlIgQAAIAAgTQgFALgLAGQgKAGgKAAQgWAAgOgPgAgXgbQgJAKAAARQAAARAJAKQAJALAPAAQAQAAAJgKQAJgKAAgRQAAgRgKgKQgKgKgPAAQgPAAgIAJg");
	this.shape_8.setTransform(78,33.1,0.521,0.521);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AAdA1IAAg7QAAgegbAAQgOgBgKALQgIANACANIAAA1IgRAAIAAhlIARAAIAAAPQAGgJAKgFQAKgFAKAAQASAAAKAKQAKAJAAARIAABFg");
	this.shape_9.setTransform(71.5,33,0.521,0.521);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_10.setTransform(64.7,33.1,0.521,0.521);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AgHBSIAAhlIAQAAIAABlgAgIg7QgEgDAAgGQAAgFAEgEQAEgEAEAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_11.setTransform(59.9,31.5,0.521,0.521);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#999999").s().p("AgUAyQgMgGgFgLIANgJQAEAIAHAEQAIAFAGgBQAJAAAGgEQAEgFAAgGQAAgGgDgEQgDgCgJgDQgWgJgHgDQgKgHAAgNQAAgOAJgIQALgJAOAAQAMgCAKAGQAKAGAFAKIgOAJQgDgHgHgEQgGgEgHAAQgGAAgFAEQgFAEgBAGIAAABQABAHAGAEQADACAQAEQAPAFAHAGQAHAHAAALQABAPgLAJQgKAJgRAAIgCAAQgLAAgIgFg");
	this.shape_12.setTransform(56.1,33.1,0.521,0.521);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#999999").s().p("AgVAyQgLgGgGgLIAPgJQAHARASgBQAIAAAGgEQAFgFAAgGQAAgGgEgEQgEgCgIgDQgXgJgFgDQgLgHAAgNQAAgOAKgIQAKgJAPAAQALgCAKAGQAKAGAFAKIgOAJQgHgQgQABQgFgBgGAEQgEAEgBAHIAAABQgBAHAHAEQADACAQAEQAPAFAHAGQAHAHABALQAAAPgKAJQgLAJgQAAIgDAAQgKAAgKgFg");
	this.shape_13.setTransform(51.2,33.1,0.521,0.521);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#999999").s().p("AACA3QgWAAgOgPQgPgQAAgYQAAgYAOgPQAOgPAWAAQAWAAANAPQAOAOAAAZIAAACIhQAAIAAACQgBAOAJALQAIALAOABIADAAQAXgBAKgVIANAJQgHANgNAHQgLAHgOAAIgCAAgAgUgfQgJAIgBAMIA9AAQAAgLgIgJQgIgIgMAAIgDAAIgBAAQgLAAgIAIg");
	this.shape_14.setTransform(45.8,33.2,0.521,0.521);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#999999").s().p("AgMBXIAAhXIgTAAIAAgOIATAAIAAgdQABgYAFgJQAGgKARAAQAGAAAJACIAAASQgFgDgJAAQgJAAgDAHQgBAEAAARIAAAcIAbAAIAAANIgbAAIAABXg");
	this.shape_15.setTransform(41.1,31.2,0.521,0.521);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("AgmAnQgQgQAAgXQAAgVAQgQIAAgBQAQgQAWAAQAXAAAQARQAQAQAAAVQAAAXgPAQIgBAAQgQAQgXAAQgWAAgQgQgAgXgbQgMALgBAQIAAAAQAAAQAKALQALALAPABIAAAAQAQABAMgLQAMgLAAgQQABgPgLgMQgLgLgQgBIgBAAQgOAAgLAKg");
	this.shape_16.setTransform(35.9,33.1,0.521,0.521);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#999999").s().p("AgeA1IAAhmIAQAAIAAAWQAHgNAHgGQAHgGAMAAQAGAAAGACIgGAQIgLgCQgbAAAAAnIAAAyg");
	this.shape_17.setTransform(30.9,33.1,0.521,0.521);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#999999").s().p("AgtBSIAAiiIAiAAQAdgBALAJQAPANACAUQABAVgNAOIgFAEQgHAFgLADIgWABIgPAAIAABJgAgagIIAKAAQAWAAAJgFQAKgGAAgPQAAgQgKgHQgKgGgVABIgKAAg");
	this.shape_18.setTransform(25.9,31.5,0.521,0.521);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#9D9D9C").s().p("AnWCpIAAioQAAglAagbQAbgbAlAAIAHAAQAlABAZAbQAZAbgBAkQgBAmgbAaQgcAbgmgBIgxAAIAABOgAmhgjQgOAQAAAUIAAAzIAzAAQAWAAAPgPQAQgQgBgVQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgUgQgOQgPgOgVAAIgBAAQgVABgPAQgAD1BAQgbgaABgmQAAgkAagbQAbgbAlAAQAmAAAbAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgmAAgbgbgAESglQgPAPgBAVQAAAVAPARQAPAQAWABIABAAQAWgBAPgQQAPgPgBgWIAAAAQAAgVgPgQQgPgQgWAAQgVABgPAPgAjyBBQgbgagBgmQAAglAagbQAbgbAlAAQAmgBAbAbQAbAaABAmIgCANIiMAAQAEASAOANQAPAMASgBQAdAAAZgSIAWAcQghAagpAAIgBAAIgCAAQglAAgagagAjRgsQgNAKgGARIBiAAQgFgQgNgLQgNgKgRAAQgRAAgOAKgAMNBbQgmAAgagbQgbgaAAglIABgBQgBgkAagbQAagbAlAAIACAAQAhgBAZAXIgXAaQgQgMgUABQgWACgPAQQgOARABAVQABAUAOAOQAOAPAVACQAUACAPgNIAZAZQgYAXggAAIgDAAgAAxA/IAVgbQAaARAgADQAgAAAAgRQAAgIgRgHIglgLQg2gPAAgjQAAgWATgPQAUgPAfAAQAmAAAfATIgUAbQgWgLgagBQgdAAAAARQAAAIA1AQQA1APAAAiQAAAbgYAPQgUANgdABQgrgCgjgagApGBbQglAAgZgZQgbgaAAgsIAAhTIAoAAIAABTQAAAbAPAPQAOAOAVABQAVgBAOgOQAPgPAAgbIAAhTIAoAAIAABTQAAArgbAaQgZAZglABgAtHA/IAWgbQAZARAhADQAfAAAAgRQAAgIgRgHIglgLQg1gPAAgjQAAgWATgPQAUgPAfAAQAlAAAgATIgUAbQgXgLgagBQgdAAAAARQAAAHARAGIAlALQA1APAAAiQAAAbgYAPQgVANgdABQgqgCgkgagAGmgHQABgkAcgaQAbgZAlABQAkABAaAbQAZAbgBAlIAABYIgoAAIAAhWQABgFgBgGQgCgUgRgNQgQgNgVACQgUADgNAQQgNAQACAUIAABWIgnABgAhDBYIAAhZQABgmAbgZQAbgbAlABIAJAAIAAAlQgHgBgIACQguAIAAAwIAABUgAJ1BXIAAiuIAoAAIAACugAKKh6QgJAAgHgGQgHgIAAgJQAAgJAHgHQAHgHAJAAQAKAAAGAHQAHAHAAAJQAAAJgGAIQgHAGgJAAg");
	this.shape_19.setTransform(100.4,9.4,0.521,0.521);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#1D1D1B").s().p("AgiCEQgbgHgVgRIAYggQAUAOAaADQAgABAOgcQAIgRAAgWQgTARgXAAQgkAAgbgaQgbgZAAglIAAhaIAwAAIAABZQAAASAMAMQANANARAAQARAAANgNQANgMAAgSIAAhZIAwAAIAABZQAABSgHAdQgPA2gzAMQgNADgNAAQgNAAgNgDg");
	this.shape_20.setTransform(15.5,11.8,0.521,0.521);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#1D1D1B").s().p("AgJBbQglgGgdgWIAXgfQALAIASAGQAXAHAQgFQALgCACgHQACgGgHgFIgggKQgbgHgNgIQgQgIgFgRQgFgRAIgRQANgYAfgIQAQgDAMACQAhABAdATIgXAfQgdgNgfAEQgIACgCAFQgCAGAGADIAAAAQAFAFAZAHQAcAHAMAGQAcAOgBAcQgBASgJALQgRAVgfAFg");
	this.shape_21.setTransform(25.3,9.4,0.521,0.521);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#1D1D1B").s().p("AArBZIAAhXQAAgRgNgMQgMgNgSAAQgRAAgNANQgMAMAAARIAABXIgvAAIAAhXQgBglAbgaQAbgbAkAAQAlAAAbAbQAaAaABAlIAABXg");
	this.shape_22.setTransform(45.2,9.3,0.521,0.521);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#1D1D1B").s().p("Ag/BAQgbgaAAgmQAAgkAbgbQAagaAlgBQAmAAAaAbQAbAaAAAlQAAAmgbAaQgaAbgmAAQgkAAgbgbgAgdgdQgNAMAAARQAAASAMANQANANARAAQASAAANgNQAMgNAAgSQAAgRgMgMQgNgNgSAAQgRAAgMANg");
	this.shape_23.setTransform(34.7,9.3,0.521,0.521);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#1D1D1B").s().p("Ag/BtQgbgbAAglQAAgmAagaQAbgaAlgBIArAAIAAhYIAwAAIAACyQgBAmgaAbQgbAaglAAQglAAgagagAgeAOQgMAMAAASQAAASAMANQANAMARAAQARAAANgMQANgNAAgSIgBgrIgqAAQgRAAgNANg");
	this.shape_24.setTransform(4.7,7.1,0.521,0.521);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Logo, new cjs.Rectangle(0,0,144.2,20.2), null);


(lib.HeadTop = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HeadShot();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.493,0.493);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.HeadTop, new cjs.Rectangle(0,0,102,102), null);


(lib.DesignedforsalonsDevelopedwithprofessionalsEngineeredbsvg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Designed for salons. Developed with professionals. Engineered b.svg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AO7CqIAqhcIg9iKIAgAAIAtBvIAwhvIAdAAIhpDmgAqNCqIAAjmIAYAAIAAAdQAEgJAIgFQAFgIAHgEIAPgHIASgCQARAAANAGQAOAGALALQAJALAFAQQAGAPAAASIgBALQgBANgEALQgFAQgJAKQgLAMgNAGQgOAFgQAAQgKAAgIgCQgIgCgIgGIgMgKQgHgGgDgIIAABngApVglQgKAFgIAHQgHAHgDAMQgEAJAAAOIABALQABAHACAGQAEAKAIAIQAFAIALAEQAKAEAMAAQALAAAJgEQAKgEAGgGQAHgHADgLIADgPIAAgIQAAgOgDgLQgEgLgGgIQgHgIgJgFQgJgDgNAAQgMAAgIADgABzgPIgyB3IhFikIAcAAIAqBpIAwhvIADAAIAwBvIAohpIAfAAIhGCkgA0Og8IAeAAIAuBsIAuhsIAfAAIhNCkgAYCBjQgJgCgIgEIgOgKQgFgGgGgJIAXgQQAHANAJAGQAKAHAOAAQAOAAAHgHQAJgHAAgKQAAgJgIgEQgEgGgNgFIgagIIgTgKQgIgGgFgHQgFgHAAgLQAAgLAFgIQAFgJAGgGQAIgGAKgEQAKgDAMAAQAKAAAJACIAPAFQAIAFAGAGIAJANIgXANQgFgKgJgGQgIgGgOAAQgLAAgIAGQgGAHAAAKQAAAMAKAEQAEADAaAIIATAHIAPAJIAFAGIADAHQADAHAAAJQAAALgEAJQgFAJgHAHQgIAHgKADQgLAEgLAAQgMAAgJgCgAUcBjQgKgCgIgEIgNgKQgGgGgGgJIAYgQQAHANAJAGQAJAHANAAQAPAAAIgHQAIgHAAgKQAAgJgHgEQgEgGgNgFIgagIIgTgKQgJgGgFgHQgEgHAAgLQAAgLAEgIQAFgJAHgGQAIgGAKgEQAJgDAMAAQALAAAIACIAQAFQAHAFAGAGIAJANIgWANQgFgKgKgGQgIgGgNAAQgMAAgHAGQgHAHAAAKQAAAMAKAEQAEADAaAIIATAHQAJAEAFAFIAGAGIADAHQADAHAAAJQABALgFAJQgFAJgGAHQgIAHgKADQgMAEgMAAQgLAAgIgCgAL1BjQgJgCgJgEQgHgFgGgFQgGgGgGgJIAYgQQAHANAIAGQALAHANAAQAOAAAHgHQAJgHAAgKQAAgJgHgEQgEgGgNgFIgagIIgTgKQgJgGgFgHQgEgHAAgLQAAgLAEgIQAFgJAHgGQAIgGAJgEQAKgDAMAAQALAAAIACIAQAFQAHAFAGAGQAFAFADAIIgVANQgGgKgIgGQgJgGgNAAQgMAAgHAGQgIAHABAKQAAAMAKAEQAEADAaAIIATAHQAJAEAGAFIAFAGIAEAHQACAHAAAJQAAALgEAJQgFAJgHAHQgHAHgKADQgMAEgLAAQgMAAgIgCgAj1BeQgNgGgKgKQgKgLgGgPQgDgLgBgNIgBgLQAAgTAFgOQAGgQAKgMQAJgKAOgGQAOgGAPAAQAKAAAJACIAOAHQAIAEAGAIQAFAFAFAJIAAiKIAcAAIAAEHIgbAAIAAgbIgKAOIgPAKQgGAFgIADQgJACgIAAQgRAAgOgHgAjngjQgJADgIAHQgFAHgFAKQgCAJAAANIABAOIABANQAFAKAFAIQAIAIAJAEQAKAEALAAQAMAAAKgEQAJgEAGgIQAIgHADgKQACgHACgHIAAgLQAAgNgEgJQgDgLgIgIQgGgHgLgEQgIgFgMAAQgLAAgKAFgAmlBeQgPgGgMgLQgKgKgGgQQgDgLgCgMIgBgMQABgSAFgOQAGgQAKgLQAMgLANgGQAOgGASAAQARAAANAGQAOAEAJAMQAKAKAHAQQADAPAAATIAAAEIh5AAIAAADIABAFQgBAJADAJQAEAKAGAIQAHAHAKAEQAJADALAAQARAAALgIQANgIAKgRIAUANQgFAMgHAHQgJAIgIAFQgJAGgKADQgMACgMAAQgRAAgOgHgAlZgBQgCgKgCgHQgDgJgHgFQgGgFgJgDQgIgDgKAAQgKAAgIADQgJADgGAGQgFAGgFAHQgEAHAAAKIBeAAIAAAAgAssBeQgPgGgNgLQgLgNgHgPQgEgKgBgLIgBgLQAAgRAGgOQAHgQALgLQANgNAPgGQAPgGARAAQARAAARAGQAOAHANAMQALALAHAQQAGAOAAARIAAALQgCALgEAKQgHAPgLALQgNANgOAGQgRAHgRAAQgQAAgQgHgAsiglQgKAFgHAIQgHAIgFALQgEAJAAANIABALIADANQAFAKAHAIQAHAIAKAEQAKAEAMAAQALAAALgEQAKgEAIgIQAIgIAFgKIACgNIABgLQAAgNgDgJQgFgLgIgIQgIgIgKgFQgLgEgLAAQgMAAgKAEgAw4BeQgOgGgMgLQgKgKgGgQQgEgLgBgMIgBgMQAAgSAGgOQAGgQAKgLQALgLANgGQAPgGASAAQARAAANAGQAPAEAIAMQAKAKAGAQQAEAPAAATIAAAEIh5AAIAAADIAAAFQAAAJADAJQAEAKAGAIQAHAHAKAEQAIADAMAAQAQAAAMgIQANgIAKgRIAUANQgFAMgHAHQgJAIgJAFQgJAGgKADQgMACgLAAQgSAAgOgHgAvrgBQgCgKgCgHQgEgJgHgFQgFgFgJgDQgJgDgKAAQgJAAgIADQgJADgGAGQgGAGgEAHQgFAHABAKIBeAAIAAAAgA2GBeQgOgGgLgLQgLgKgFgQQgFgLgBgMIgBgMQAAgSAHgOQAFgQALgLQALgLANgGQAPgGARAAQARAAANAGQAPAEAJAMQAKAKAGAQQAEAPAAATIAAAEIh6AAIAAADIABAFQAAAJACAJQAEAKAGAIQAHAHALAEQAIADALAAQAQAAAMgIQANgIALgRIAUANQgGAMgHAHQgJAIgIAFQgKAGgJADQgMACgMAAQgRAAgPgHgA05gBQgBgKgDgHQgDgJgIgFQgFgFgJgDQgJgDgJAAQgJAAgJADQgIADgHAGQgFAGgFAHQgEAHAAAKIBeAAIAAAAgAZ+BbQgFgGAAgHQAAgIAFgGQAIgGAHAAQAJAAAGAGQAFAGAAAIQAAAHgFAGQgGAGgJAAQgIAAgHgGgAWUBeIAAiEIgdAAIAAgWIAdAAIAAg+IAaAAIAAA+IAdAAIAAAWIgdAAIAACEgASwBeIAAiaIAaAAIAACagARcBeIAAkHIAaAAIAAEHgANsBeIAAiEIgcAAIAAgWIAcAAIAAg+IAbAAIAAA+IAdAAIAAAWIgdAAIAACEgAInBeIAAhbQgBgLgBgIQgDgJgEgGQgGgGgIgDQgGgDgMAAQgMAAgKAFQgIAEgIAHQgGAIgBALQgBAHgBAPIAABQIgaAAIAAkHIAaAAIAACEQALgOANgIQAOgHATAAQANAAALADQALAEAHAIQAIAHADAKQAFAKAAANIAABpgAFgBeIAAiEIgeAAIAAgWIAeAAIAAg+IAaAAIAAA+IAdAAIAAAWIgdAAIAACEgAEIBeIAAiaIAbAAIAACagAulBeIAAkHIAaAAIAAEHgA6hBeIAAj4IAwAAQAYAAAnADQAPADALAEQANAGAKAHQAMAJAHALQAHAJAFAKIACAEQAHAMAAAQQADAPABAPQgBASgDANQgBAOgFANIgBABQgFANgJAKQgHAKgMAJQgKAHgMAGIgYAHQgjADgVAAgA6EBDIATAAQAnAAAQgDQAMgCAJgDQAKgEAHgGQAJgHAFgHIAFgHIAEgMQAFgKADgLQABgLAAgOQAAgNgBgLQgDgMgFgKQgCgIgGgIIgBgBQgFgJgJgGQgHgGgIgEQgLgEgMgCQgQgDgnAAIgTAAgASvh5QgGgGAAgIQAAgIAGgFQAFgGAJAAQAHAAAGAGQAGAFAAAIQAAAIgGAGQgGAGgHAAQgJAAgFgGgAEIh5QgHgGAAgIQAAgIAHgFQAFgGAJAAQAHAAAGAGQAGAFAAAIQAAAIgGAGQgGAGgHAAQgJAAgFgGg");
	this.shape.setTransform(169.8,62);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AyPJpQglAAgUgRQgUgRgBgeIAfAAIAAACQAAASAMAKQANAKAXAAQAhAAANgVQAIgSgBgTIAAgbQgJAQgQAKQgPAKgTgBQgiAAgVgXQgWgYAAgnQAAgnAVgYQAVgWAiAAQATgBAQAKQAQAJAIARIAAgeIAcAAIAACfQAAAVgCAKQgEAPgKAKQgYAZgiAAIgHAAgAy2GeQgOAPAAAbQAAAdAOAQQAOAQAaAAQAYAAAOgPQAPgQAAgbQAAgcgQgRQgPgQgXAAQgZAAgOAQgANoJpIAsheIg/iRIAgAAIAuBzIAyhzIAeAAIhsDvgAF1JpIAsheIg/iRIAfAAIAvBzIAyhzIAeAAIhsDvgAjXIhQglAAgXgYQgWgYAAgoQAAgmAWgYQAXgYAjAAQAkAAAUAXQAVAXAAAoIAAAFIh/AAIAAADQAAAaAPAQQAPAPAXAAQAhAAATgjIAVAOQgKAVgUAMQgTALgWAAIgDAAgAipG4QgCgVgNgMQgMgLgWAAQgTgBgPANQgOANgBATIBiAAIAAAAgAoBIhQglAAgXgYQgXgYAAgoQAAgmAXgYQAWgYAkAAQAjAAAVAXQAVAXAAAoIAAAFIh/AAIAAADQAAAaAPAQQAOAPAYAAQAgAAAUgjIAVAOQgLAVgUAMQgSALgWAAIgDAAgAnTG4QgCgVgNgMQgMgLgWAAQgUgBgOANQgOANgBATIBiAAIAAAAgAq5IhQglAAgXgYQgWgYAAgoQAAgmAWgYQAXgYAjAAQAkAAAVAXQAVAXAAAoIAAAFIiAAAIAAADQAAAaAPAQQAPAPAXAAQAhAAAUgjIAVAOQgLAVgUAMQgTALgWAAIgDAAgAqLG4QgBgVgNgMQgNgLgWAAQgTgBgOANQgPANgBATIBiAAIAAAAgASlIIQgbgaABgjQgBglAbgZQAagaAkABQAlAAAYAZIABABQAZAZAAAkQAAAkgaAZQgZAZgkAAIgDAAQgjAAgYgZgAS7GiQgSAQgBAZIAAABQAAAYARASQARARAZAAQAXAAARgQQARgQABgXQABgYgRgSQgQgSgYgBIgDAAQgWAAgRAPgAP6H/IAXgPQAFAMAMAHQALAHANgBQAOAAAIgGQAIgHAAgLQAAgQgZgIQglgNgJgHQgRgLAAgWQAAgVAQgNQAPgOAaAAQArAAAOAgIgWANQgFgLgKgGQgKgGgMAAIgCAAQgKAAgIAHQgHAHAAALQAAALAKAGQAFACAaAIQAZAIAKAKQAMALAAATQAAAXgQAOQgQAOgbAAQgtAAgSgigADpIYQgPgKgJgRIAAAeIgaAAIAAkRIAbAAIAACOQAIgRAQgKQAQgKATABQAiAAAVAXQAVAYAAAoQAAAngVAYQgWAXgiAAQgTAAgQgJgADgGgQgPAQAAAbQAAAcAPAQQAOAQAZAAQAZAAAOgRQAOgRAAgeQAAgagOgPQgOgPgYAAQgZAAgPARgAhbIKQgWgYAAgnQAAgoAVgYQAVgXAiAAQATgBAQAKQAPAKAIARIAAiOIAbAAIAAERIgaAAIAAgeQgJARgPAKQgPAJgTAAQgiAAgVgXgAhGGeQgOAPAAAaQAAAeAPARQANARAZAAQAZAAANgQQAPgQAAgcIgBAAQAAgbgPgQQgNgRgZAAQgYAAgOAPgAY3IeIgBAAQgIAAgGgGQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJgBAGAHQAHAGAAAIIAAABQgBAIgGAGQgFAGgIAAIgBAAgAXWIbIAAhfQAAgwgrAAQgYgCgPATQgHAIgCALIgBAXIAABUIgbAAIAAihIAbAAIAAAYQAKgPAPgIQAQgIASABQAcAAAQAPQAQAPAAAbIAABugAmRIbIAAihIAZAAIAAAhQALgVAMgJQANgJASAAQAJAAAJADIgJAZQgIgDgJAAQgsAAAAA/IAABPgAtKIbIAAhfQAAgwgrAAQgYgCgPATQgHAIgCALIgBAXIAABUIgbAAIAAihIAbAAIAAAYQAKgPAPgIQAQgIASABQAcAAAQAPQAQAPAAAbIAABugAwOIbIAAihIAcAAIAAChgAJrIaIAAkBIAyAAQAtAAATADQAfAFAVAQQAtAjAABGQAABGgtAiQgUAQgcAFQgTADgmAAgAKKH+IAUAAQAoAAAQgDQAZgDAPgNQAggaAAg3QAAg3gggbQgPgMgYgEQgSgDgnAAIgUAAgA0hIaIAAheQAAgwgrAAQgYgCgPATQgHAIgCALIgBAXIAABTIgbAAIAAigIAbAAIAAAYQAKgPAPgIQAQgIARABQAdAAAQAPQAQAPAAAbIAABtgA5LIaIAAkBICIAAIAAAcIhpAAIAABKIBpAAIAAAcIhpAAIAABjIBpAAIAAAcgAwAFAQgIAAgGgGQgGgFAAgJQAAgIAGgGQAGgGAIAAQAJAAAFAGQAGAGAAAIQAAAJgGAGQgFAFgIAAIgBAAgAsOkGQglAAgUgRQgUgRgBgeIAfAAIAAACQAAASAMAKQAMAKAYAAQAhAAANgVQAIgSgCgTIAAgbQgIAQgQAKQgPAKgTAAQgiAAgVgYQgWgYAAgnQAAgnAVgYQAVgWAiAAQASgBARAKQAPAJAJARIAAgdIAcAAIAACeQAAAVgCAKQgEAPgKAKQgZAZggAAIgIAAgAs1nRQgOAPAAAbQAAAdAOAQQAOAQAaAAQAYAAAOgPQAOgQAAgbQAAgcgPgRQgPgQgXAAQgZAAgOAQgAmGlOQgkAAgXgYQgXgYAAgoQAAgmAXgYQAWgYAkAAQAjAAAVAXQAVAXAAAoIAAAFIh/AAIAAADQAAAaAPAQQAOAPAYAAQAgAAAUgjIAVAOQgLAVgUAMQgTALgVAAIgEAAgAlYm3QgBgVgNgMQgMgLgXgBQgTAAgOANQgOANgCATIBiAAIAAAAgAyglOQglAAgXgYQgWgYAAgoQAAgmAWgYQAXgYAjAAQAkAAAVAXQAVAXAAAoIAAAFIiAAAIAAADQAAAaAPAQQAPAPAXAAQAhAAAUgjIAUAOQgKAVgUAMQgTALgWAAIgDAAgAxym3QgBgVgNgMQgNgLgWAAQgTgBgPANQgOANgBATIBiAAIAAAAgAOulnQgagZAAgkQAAgkAagaQAagaAkABQAkAAAaAZIAAABQAZAZAAAkQAAAkgZAZQgaAZgkAAIgDAAQgiAAgZgZgAPEnNQgSAQgBAZIAAABQAAAYARASQARARAZAAQAXAAARgQQARgQABgXQABgYgQgSQgRgSgYgBIgDAAQgWAAgRAPgAB4lnQgagZAAgkQAAglAagZQAagaAkABQAlAAAZAZIABABQAZAZAAAkQgBAkgZAZQgaAZgkAAIgDAAQgiAAgZgZgACPnNQgSAQgBAZIAAABQgBAYARASQARARAZAAQAXAAARgQQARgQABgXQABgYgQgSQgQgSgZgBIgDAAQgWAAgQAPgAUalwIAXgPQAGAMALAHQALAHANgBQAOAAAIgGQAJgHAAgLQAAgQgagIQglgNgJgHQgRgLAAgWQAAgVAQgNQAQgOAZAAQAVAAAPAIQAPAIAGAQIgWAOQgFgLgKgHQgKgGgMAAIgCAAQgKAAgHAHQgIAHAAALQAAALALAGQADACAbAIQAZAIALAKQALALAAATQAAAXgQAOQgQAOgbAAQgsAAgTgigAKWllQgWgYAAgnQAAgoAVgYQAVgXAiAAQATgBAQAKQAQAJAIASIAAgfIAbAAIAAChIgaAAIAAgdQgJARgPAKQgQAJgTAAQgiAAgVgXgAKrnRQgNAQAAAbQAAAdAOAQQANAQAaAAQAZAAAOgPQAOgQAAgbQAAgcgPgRQgPgQgYAAQgZAAgOAPgAHulwIAYgPQAFAMALAHQALAHAOgBQANAAAJgGQAIgHAAgLQAAgQgZgIQglgNgKgHQgRgLAAgWQAAgVAQgNQAQgOAZAAQAVAAAPAIQAPAIAGAQIgWAOQgFgLgKgHQgKgGgMAAIgCAAQgKAAgHAHQgIAHAAALQAAALALAGQADACAbAIQAZAIALAKQALALAAATQAAAXgQAOQgQAOgaAAQgtAAgTgigAkKllQgVgYAAgnQAAgoAVgYQAVgXAiAAQASgBAQAKQAQAKAIARIAAiOIAcAAIAAERIgbAAIAAgeQgIARgQAKQgQAJgSAAQgjAAgVgXgAj0nRQgOAPAAAaQAAAeAOARQAOARAYAAQAZAAAPgQQAOgQAAgcQAAgbgPgQQgPgRgYAAQgYAAgOAPgAw/lwIAXgPQAGAMALAHQALAHANgBQAOAAAIgGQAIgHAAgLQAAgQgZgIQglgNgJgHQgRgLAAgWQAAgVAPgNQAQgOAaAAQArAAAOAgIgWANQgFgLgKgGQgKgGgMAAIgCAAQgKAAgIAHQgHAHgBALQAAALALAGIAfAKQAZAIAKAKQAMALAAATQAAAXgQAOQgQAOgbAAQgtAAgSgigAXQlRIAAAAQgJAAgGgGQgGgGAAgJQAAgIAGgHQAHgGAIAAQAJAAAGAGQAGAHAAAIIAAABQAAAIgGAGQgGAGgHAAIgCAAgATflUIAAhfQAAgwgrAAQgXgCgQATQgGAIgCALIgBAXIAABUIgcAAIAAihIAcAAIAAAYQAJgPAQgIQAPgIASABQAcAAAQAPQAQAPAAAbIAABugAEzlUIAAihIAYAAIAAAhQALgUAMgKQANgJASAAQAKAAAJADIgKAZQgHgDgJAAQgsAAAAA/IAABPgANTlVIAAkQIAbAAIAAEQgAAQlVIAAiKIgeAAIAAgWIAeAAIAAgvQAAgmAJgOQAJgQAcAAQANAAALADIAAAdQgKgGgMAAQgOAAgEALQgDAIAAAbIAAArIArAAIAAAWIgrAAIAACKgAoXlVIAAheQAAgxgrAAQgYgBgPATQgGAIgCALIgBAXIAABTIgcAAIAAigIAcAAIAAAYQAJgPAQgIQAQgIARABQAdAAAQAPQAQAPAAAbIAABtgAuhlVIAAigIAbAAIAACggA3klVIAAkBIAxAAQAtAAAUADQAfAFAVAQQAtAjAABGQAABGgtAiQgVAQgcAFQgTADgmAAgA3GlxIAUAAQAoAAARgDQAZgDAOgNQAhgaAAg3QAAg3ghgbQgOgMgZgEQgSgDgnAAIgUAAgAuio1QgGgFAAgJIAAAAQAAgIAGgGQAGgGAIAAQAJAAAFAGQAGAGAAAIQAAAIgGAGQgFAGgIAAQgJAAgGgGg");
	this.shape_1.setTransform(169.8,61.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,339.5,123.4);


(lib.BLK = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Blk();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.BLK, new cjs.Rectangle(0,0,32,32), null);


(lib.EndText1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.DesignedforsalonsDevelopedwithprofessionalsEngineeredbsvg("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(110.6,30.9,0.5,0.5,0,0,0,221.2,61.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.EndText1, new cjs.Rectangle(0,0,169.8,61.7), null);


// stage content:
(lib.C_DMPU_Stage4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_269 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(269).call(this.frame_269).wait(1));

	// Strap
	this.instance = new lib.Strap();
	this.instance.parent = this;
	this.instance.setTransform(149.8,42.7,1.45,1.45,0,0,0,72.4,18.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).to({y:47.7,alpha:1},8).wait(243));

	// CTA.svg
	this.instance_1 = new lib.NEW_CTA();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,202.5,1,1,0,0,0,60,17.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(247).to({_off:false},0).to({y:207.5,alpha:1},6).wait(17));

	// EndText
	this.instance_2 = new lib.EndText1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(175.8,129.1,1,1,0,0,0,110.6,30.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(241).to({_off:false},0).to({y:134.1,alpha:1},6).wait(23));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#888888").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	// NewQuote.svg
	this.instance_3 = new lib.NewerQuote();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,336.8,1,1,0,0,0,113.3,33.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(83).to({_off:false},0).to({alpha:1},11).wait(58).to({alpha:0},6).to({_off:true},1).wait(111));

	// Blk copy (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_59 = new cjs.Graphics().p("EAAAgvpMAu4AAAMAAABfTMgu4AAAg");
	var mask_graphics_60 = new cjs.Graphics().p("EgEGgvpMAvIAAAMAAABfTMgvIAAAg");
	var mask_graphics_61 = new cjs.Graphics().p("EgIMgvpMAvYAAAMAAABfTMgvYAAAg");
	var mask_graphics_62 = new cjs.Graphics().p("EgMTgvpMAvqAAAMAAABfTMgvqAAAg");
	var mask_graphics_63 = new cjs.Graphics().p("EgQZgvpMAv6AAAMAAABfTMgv6AAAg");
	var mask_graphics_64 = new cjs.Graphics().p("EgUggvpMAwLAAAMAAABfTMgwLAAAg");
	var mask_graphics_65 = new cjs.Graphics().p("EgYNgvpMAwbAAAMAAABfTMgwbAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(59).to({graphics:mask_graphics_59,x:300,y:300}).wait(1).to({graphics:mask_graphics_60,x:275.4,y:300}).wait(1).to({graphics:mask_graphics_61,x:250.8,y:300}).wait(1).to({graphics:mask_graphics_62,x:226.3,y:300}).wait(1).to({graphics:mask_graphics_63,x:201.7,y:300}).wait(1).to({graphics:mask_graphics_64,x:177.1,y:300}).wait(1).to({graphics:mask_graphics_65,x:150,y:300}).wait(205));

	// White
	this.instance_4 = new lib.White();
	this.instance_4.parent = this;
	this.instance_4.setTransform(151.2,43,1.44,1.44,0,0,0,72.8,15.1);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(59).to({_off:false},0).to({_off:true},14).wait(197));

	// Blk MaskOut (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_230 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_231 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_232 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_233 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_234 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_235 = new cjs.Graphics().p("EgXbgvpMAu3AAAMAAABfTMgu3AAAg");
	var mask_1_graphics_236 = new cjs.Graphics().p("EgX+gvpMAu3AAAMAAABfTMgu3AAAg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(230).to({graphics:mask_1_graphics_230,x:150,y:305}).wait(1).to({graphics:mask_1_graphics_231,x:98.8,y:305}).wait(1).to({graphics:mask_1_graphics_232,x:47.7,y:305}).wait(1).to({graphics:mask_1_graphics_233,x:-3.5,y:305}).wait(1).to({graphics:mask_1_graphics_234,x:-54.7,y:305}).wait(1).to({graphics:mask_1_graphics_235,x:-105.8,y:305}).wait(1).to({graphics:mask_1_graphics_236,x:-153.5,y:305}).wait(34));

	// White
	this.instance_5 = new lib.White();
	this.instance_5.parent = this;
	this.instance_5.setTransform(151.2,43,1.44,1.44,0,0,0,72.8,15.1);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(73).to({_off:false},0).to({_off:true},164).wait(33));

	// JobTitle
	this.instance_6 = new lib.Text();
	this.instance_6.parent = this;
	this.instance_6.setTransform(545.4,212,1,1,0,0,0,119.9,106.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(158).to({_off:false},0).to({alpha:1},6).to({_off:true},73).wait(33));

	// HeadTop
	this.instance_7 = new lib.HeadTop();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150.1,210.3,0.999,0.999,0,0,0,51.1,51.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(83).to({_off:false},0).to({alpha:1},11).to({_off:true},143).wait(33));

	// Blk
	this.instance_8 = new lib.BLK();
	this.instance_8.parent = this;
	this.instance_8.setTransform(450,300,9.375,19.062,0,0,0,16,16);
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(59).to({_off:false},0).to({scaleX:9.69,x:150},6).to({_off:true},172).wait(33));

	// ProductShot_LockUp
	this.instance_9 = new lib.Logo();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150.5,37.5,1.44,1.44,0,0,0,72.4,18.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(11).to({_off:false},0).to({y:47.5,alpha:1},3).wait(256));

	// Layer 4
	this.instance_10 = new lib.zoomOutCover();
	this.instance_10.parent = this;
	this.instance_10.setTransform(148.1,305.7,0.991,0.991,0,0,0,267.2,267.2);
	this.instance_10.alpha = 0.59;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(3).to({alpha:1},0).to({regX:267.4,regY:267.4,scaleX:0.1,scaleY:0.1,x:149.6,y:211,alpha:0},11).wait(256));

	// ProductShot
	this.instance_11 = new lib.ProductShot_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(148.7,1195.6,9.973,9.973,0,0,0,149.7,299.8);

	this.instance_12 = new lib.NewBG();
	this.instance_12.parent = this;
	this.instance_12.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_11}]}).to({state:[{t:this.instance_11}]},3).to({state:[{t:this.instance_11}]},11).to({state:[]},68).to({state:[{t:this.instance_12}]},128).wait(60));
	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(3).to({regX:150,regY:300,scaleX:1,scaleY:1,x:150,y:300.5},11).to({_off:true},68).wait(188));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1194.2,-1494.1,2991.8,5983.5);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/Blk.png", id:"Blk"},
		{src:"images/HeadShot.png", id:"HeadShot"},
		{src:"images/NewBG.jpg", id:"NewBG"},
		{src:"images/ProductShot.jpg", id:"ProductShot"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;